<?php

header("Content-Type: application/json; charset=UTF-8");

$databaseUrl = getenv('DATABASE_URL');

if (!$databaseUrl) {
    http_response_code(500);
    echo json_encode([
        'success' => false,
        'message' => 'DATABASE_URL is not configured.'
    ]);
    exit;
}

$parts = parse_url($databaseUrl);

if (
    $parts === false ||
    empty($parts['host']) ||
    empty($parts['user']) ||
    !isset($parts['pass']) ||
    empty($parts['path'])
) {
    http_response_code(500);
    echo json_encode([
        'success' => false,
        'message' => 'Invalid DATABASE_URL.'
    ]);
    exit;
}

$host = $parts['host'];
$port = $parts['port'] ?? 5432;
$dbname = ltrim($parts['path'], '/');
$username = $parts['user'];
$password = $parts['pass'];

try {
    $dsn = "pgsql:host={$host};port={$port};dbname={$dbname};sslmode=require";

    $pdo = new PDO($dsn, $username, $password, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
    ]);

    /*
     * Auto-create the EcoSwap schema.
     * This makes a fresh Neon database ready without
     * requiring database.sql to be run manually.
     */
    $pdo->exec("
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(100) NOT NULL,
            email VARCHAR(150) NOT NULL UNIQUE,
            password VARCHAR(255) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS items (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            name VARCHAR(150) NOT NULL,
            category VARCHAR(50) NOT NULL,
            item_condition VARCHAR(50) NOT NULL,
            description TEXT,
            image VARCHAR(255),
            status VARCHAR(20) NOT NULL DEFAULT 'available'
                CHECK (status IN ('available', 'pending', 'swapped')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS swap_requests (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
            requester_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            message TEXT,
            status VARCHAR(20) NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'accepted', 'rejected', 'cancelled')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE INDEX IF NOT EXISTS idx_items_category ON items(category);
        CREATE INDEX IF NOT EXISTS idx_items_status ON items(status);
        CREATE INDEX IF NOT EXISTS idx_swap_item ON swap_requests(item_id);
        CREATE INDEX IF NOT EXISTS idx_swap_requester ON swap_requests(requester_id);
        CREATE INDEX IF NOT EXISTS idx_swap_owner ON swap_requests(owner_id);

        CREATE OR REPLACE FUNCTION update_swap_requests_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = CURRENT_TIMESTAMP;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        DROP TRIGGER IF EXISTS trg_swap_requests_updated_at ON swap_requests;

        CREATE TRIGGER trg_swap_requests_updated_at
        BEFORE UPDATE ON swap_requests
        FOR EACH ROW
        EXECUTE FUNCTION update_swap_requests_updated_at();
    ");

} catch (PDOException $e) {
    http_response_code(500);
    echo json_encode([
        'success' => false,
        'message' => 'Database connection or setup failed.',
        'error' => $e->getMessage()
    ]);
    exit;
}
