<?php

declare(strict_types=1);

/**
 * Neon PostgreSQL connection.
 * Render must provide DATABASE_URL. NEON_DATABASE_URL is accepted as a fallback.
 */
function db(): PDO
{
    static $pdo = null;
    if ($pdo instanceof PDO) return $pdo;

    $url = getenv('DATABASE_URL');
    if ($url === false || trim($url) === '') {
        $url = getenv('NEON_DATABASE_URL');
    }

    if ($url === false || trim($url) === '') {
        throw new RuntimeException('DATABASE_URL is not configured on Render.');
    }

    $url = trim($url);
    // Allow accidental surrounding quotes when copied into an environment variable.
    if ((str_starts_with($url, '"') && str_ends_with($url, '"')) ||
        (str_starts_with($url, "'") && str_ends_with($url, "'"))) {
        $url = substr($url, 1, -1);
    }

    // Neon provides postgres:// or postgresql:// URLs.
    if (!preg_match('#^postgres(?:ql)?://#i', $url)) {
        throw new RuntimeException('DATABASE_URL must be a PostgreSQL connection string.');
    }

    $parts = parse_url($url);
    if ($parts === false || empty($parts['host']) || empty($parts['user']) ||
        !array_key_exists('pass', $parts) || $parts['pass'] === null || empty($parts['path'])) {
        throw new RuntimeException('Invalid DATABASE_URL. Copy the full Neon PostgreSQL connection string.');
    }

    $host = $parts['host'];
    $port = (int)($parts['port'] ?? 5432);
    $name = ltrim($parts['path'], '/');
    $user = rawurldecode($parts['user']);
    $pass = rawurldecode($parts['pass']);

    // Keep Neon SSL mandatory. The query string from Neon may contain other options;
    // sslmode=require here guarantees encryption regardless of those options.
    $dsn = sprintf(
        'pgsql:host=%s;port=%d;dbname=%s;sslmode=require',
        $host,
        $port,
        $name
    );

    try {
        $pdo = new PDO($dsn, $user, $pass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false,
        ]);
    } catch (PDOException $e) {
        error_log('Neon PostgreSQL connection failed: ' . $e->getMessage());
        throw new RuntimeException('Unable to connect to Neon PostgreSQL. Check Render DATABASE_URL.');
    }

    initialize_database($pdo);
    return $pdo;
}

function initialize_database(PDO $pdo): void
{
    // Run each statement separately so one DDL statement cannot prevent later
    // migrations from being applied on a fresh or existing Neon database.
    $statements = [
        "CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(100) NOT NULL,
            email VARCHAR(150) NOT NULL UNIQUE,
            password VARCHAR(255) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )",
        "CREATE TABLE IF NOT EXISTS items (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            name VARCHAR(150) NOT NULL,
            category VARCHAR(50) NOT NULL,
            item_condition VARCHAR(50) NOT NULL,
            description TEXT,
            image VARCHAR(255),
            image_data BYTEA,
            image_mime VARCHAR(50),
            phone VARCHAR(30),
            location VARCHAR(255),
            status VARCHAR(20) NOT NULL DEFAULT 'available' CHECK (status IN ('available','pending','swapped')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )",
        "CREATE TABLE IF NOT EXISTS swap_requests (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
            requester_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            message TEXT,
            status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected','cancelled')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )",
        "CREATE TABLE IF NOT EXISTS conversations (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
            owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            requester_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            status VARCHAR(20) NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(item_id, requester_id)
        )",
        "CREATE TABLE IF NOT EXISTS messages (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
            sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            body TEXT NOT NULL,
            offer_price NUMERIC(12,2),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )",
        "ALTER TABLE items ADD COLUMN IF NOT EXISTS image_data BYTEA",
        "ALTER TABLE items ADD COLUMN IF NOT EXISTS image_mime VARCHAR(50)",
        "ALTER TABLE items ADD COLUMN IF NOT EXISTS phone VARCHAR(30)",
        "ALTER TABLE items ADD COLUMN IF NOT EXISTS location VARCHAR(255)",
        "CREATE INDEX IF NOT EXISTS idx_items_category ON items(category)",
        "CREATE INDEX IF NOT EXISTS idx_items_status ON items(status)",
        "CREATE INDEX IF NOT EXISTS idx_items_location ON items(location)",
        "CREATE INDEX IF NOT EXISTS idx_swap_item ON swap_requests(item_id)",
        "CREATE INDEX IF NOT EXISTS idx_swap_requester ON swap_requests(requester_id)",
        "CREATE INDEX IF NOT EXISTS idx_swap_owner ON swap_requests(owner_id)",
        "CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id, created_at)",
        "CREATE INDEX IF NOT EXISTS idx_conversations_user ON conversations(owner_id, requester_id, updated_at)"
    ];

    foreach ($statements as $sql) {
        try {
            $pdo->exec($sql);
        } catch (PDOException $e) {
            error_log('Database initialization failed: ' . $e->getMessage());
            throw new RuntimeException('Neon database setup failed. Check that DATABASE_URL points to the correct Neon database.');
        }
    }
}
